workflows:
  android-build:
    name: Build Android APK

    # 设定 Flutter 环境
    environment:
      flutter: stable

    # 指定 BuJuan 项目主目录为工作目录
    working_directory: bujuan

    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build release APK
        script: |
          flutter build apk --release

    artifacts:
      # 输出的 APK 在 bujuan/build/... 下
      - build/app/outputs/flutter-apk/app-release.apk
